language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r dev-requirements.txt
  - pip install flake8

before_script:
   flake8 tic_tac_toe

script:
  - "PYTHONPATH=. py.test --cov=tic_tac_toe tests"

notifications:
  webhooks:
    urls:
      - https://rmotr.com/api/v1/webhooks/travis/project-resolved
    on_success: always
    on_failure: never
    on_start: never
